### ISSUE TITLE
[0.3.4] crashes dedicated server on login

### ISSUE THREAD

**Issue by kreezxil** [vpzomtrrfrt/exparvis#3] opened 2017-07-30 13:53 UTC
https://gist.github.com/d504e62d444702f7549b8f6456d0cec1

**Comment by vpzomtrrfrt** [comment] 2017-08-01 01:17
Uh, how did this happen?  Looks like the Melter's tile entity got attached to a block from Actually Additions

**Comment by vpzomtrrfrt** [comment] 2019-09-16 04:07
I don't think I can do anything about this unless you can reproduce it from a fresh world, so I'm going to close this issue for now

**Closed as completed by vpzomtrrfrt** 2019-09-16 04:07 UTC
